POST http://localhost:4004/odata/v4/z-service-employee-info/addEmployee
Content-Type: application/json

{
  "basicInfo": {
    "employeeID": 109,
    "firstName": "Divya",
    "lastName": "Shukla",
    "jobTitle": "Cloud Engineer"
  },
  "details": {
    "gender": "Female",
    "email": "divya.shukla@example.com",
    "department": "Cloud Services",
    "employmentType": "Full Time",
    "maritalStatus": "unmarried",
    "salary": 85000,
    "birthDate": "1993-11-12",
    "hireDate": "2023-07-01",
    "address": "55 Gomti Nagar",
    "city": "Lucknow",
    "region": "UP",
    "postalCode": "226010",
    "country": "India",
    "phoneNumber": "9823456781",
    "emergencyContactName": "Prakash Shukla",
    "emergencyContactPhone": "9823456782",
    "reportsTo": "Manager009"
  }
}




###Update MoreInfo 
POST http://localhost:4004/odata/v4/z-service-employee-info/updateMoreInfo
Content-Type: application/json

{
  "details": {
    "employeeID": 102,
    "email":"kumar@gmail.com",
    "department": "R&D",
    "salary": 55000,
    "phoneNumber": "9123456789"
  }
}

###Delete API
POST http://localhost:4004/odata/v4/z-service-employee-info/deleteEmployee
Content-Type: application/json

{
  "employeeID": 101
}
